fus-marcom/resource-center

- .eslintrc
- src/App.js
- src/App.test.js
- src/fusTheme.js
- src/index.js
I also added .eslintrc for ESLint (install it in Atom) which uses the create-react-app linting rules.
More info about the Linter [here](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#syntax-highlighting-in-the-editor).
> Proper theme usage

- src/App.js
I just refactored the MenuItems into a functional stateless component.
> Refactor MenuItems in side navigation

- public/index.html
- src/App.css
- src/App.js
- src/SideNav.js
- src/views/Glossary.js
- src/views/Home.js
- src/views/Letterhead.js
- src/views/Logos.js
- src/views/LogosPosters.js
- src/views/NotFound.js
- src/views/PlanningGuide.js
- src/views/Posters.js
- src/views/ServiceRequest.js
- src/views/Services.js
- src/views/Story.js
- src/views/Tutorial.js
Side Nav Bar has it's own component and there is a easy way to add or remove links.
Router now renders a components from the views folder instead of a render function.
Added a `background-color` to the active class (change it to the desired color).
Changed the title from "React App" to "Resource Center".
I also wanted to add React Helmet to dynamically change the title based on the render component but I didn't know if you wanted it.
#Edit:
- Added a Not Found component for bad links.
The linting stuff gave me some headache when I was trying to commit but managed to fix the errors.
See you in the livestream (hopefully).
Sebastian.
> Refactoring Components

- src/SideBarItem.js
- src/SideNav.js
To add hover event in SideBar , I use Selectable list (http://www.material-ui.com/v0.18.6/#/components/list). You can check it now. I set default backgroundColor when hover is Red. You can change it if you want.
> Create element to allow you can customize hover event

- src/components/GenericCard.js
- src/views/Logos.js
Hey Jesse, this is a sample of the card you mentioned in today's stream. Check it out. I created a new branch in my repo, so creating a PR in master branch. Hope you like it and let me know if you want me to do something more with it.
> Generic Card sample

- package.json
- src/App.test.js
- src/fusTheme.js
- src/registerServiceWorker.js
- src/views/Home.test.js
Some end-to-end testing with [nightmare](https://github.com/segmentio/nightmare) package. You basically test user stories automatically.
Remember to do npm install to download the new dependency.
> End-to-end testing

- src/views/ServiceRequest.js
- Change some let to const in ServiceRequest
- Pull target element from event instead of using document.getElementById in ServiceRequest > handleFilePath
> Minor cleaning

- src/views/Tutorial.js
You actually solved the scrollbar thing while I did it so i just rebased my commit on yours and solved conflicts.
> Auto-calculate the pixels inside calc().

- src/views/Home.test.js
- src/views/Letterhead.test.js
- src/views/NotFound.test.js
- src/views/ServiceRequest.test.js
- src/views/Tutorial.test.js
Slowly but surely making a specification of what should do the site, right inside the code. Isn't that cool?
- Test tutorial view
- Fix test that check whether a page loads or not
- Test that nonsense urls should render the Page not found view
What I have been adding is called end-to-end testing. In this kind of testing you actually use a browser to (automatically) access the site and check some facts about the page. You can even click around and type in the page to check whether things are actually working. We are using nightmare which uses electron which uses chromium.
It can tell you what is not working but not much about where is the code that its not working.
In this kind of testing you test individual parts of the code. In the case of a react project we are talking about testing …
> Some more e2e testing

- package.json
- server.js
- src/server.test.js
- Organize the server code a little bit better
- Add some testing code for the server
- Prevent emails from being sent when the tests run
I was thinking that I accidentally spammed you with mails when I was testing but then I remembered that I don't actually have an API key. 😌
> Custom server refactor

- src/views/ServiceRequest.js
Since you said you wanted to do a modal when the request is sent I went ahead and made one.
- Moved the form state to a sub-object called form so that it wouldn't mix with some state I needed for the dialogs
- Show a modal loading dialog right after you press submit
- Show a result dialog containing either the success message or the error if any. You can dismiss it by clicking "Ok", pressing enter or clicking anywhere outside the dialog
I am little bit excited with this change since it is more visible than the ones I've made before. Hope it helps
> Service request modal

- src/views/Logos.js
- src/views/ServiceRequest.test.js
Now even if you fail some tests the "test-upload.txt" will be ignored by git since is in the uploads folder
> test-upload.txt file is now uploaded in the uploads folder

- src/components/GenericCard.js
Simple refactoring similar to others I have submitted.
> Refactor GenericCard

- package.json
- src/components/GenericCard.js
You just need to remember to add these to the standard globals in `package.json`. This might be a little hacky, but it resolves the linting issues.
> Fix linting errors

- src/views/ServiceRequest.js
Because Material-UI was complaining in the console...
Btw.. I'm working in a client side form validation but couldn't figure it out yet on how to do it. Will keep trying.
> Added an ID to the TextField

- package.json
- src/components/SideNav.js
- src/data/serviceRequestFields.js
- src/img/info.svg
- src/styles/App.scss
- src/styles/inputFile.scss
- src/views/ServiceRequest.js
- yarn.lock
This is not completed so don't push it to the `master` branch.
I'm submitting this to see if someone has a better idea of how to do it, this is just the beginning.
1. Added [`formsy-react`](https://github.com/christianalfoni/formsy-react) and [`formsy-material-ui`](https://github.com/rojobuffalo/formsy-material-ui) to do some Validations. Check their docs for more info.
2. Had to modify how `singleLineFields` and ` multiLineFields` are rendered. ~~Some refractoring can be applied in the future.~~
3. This PR also includes the changes added in PR #53.
4. The code is pretty easy to understand. Here are the error validators from [`formsy`](https://github.com/christianalfoni/formsy-react/blob/master/API.md#validators).
5. There are some styleing bugs when field errors are displayed and I did …
> Client Side Validation

- README.md
Added links to resources & tutorials for beginners who want to learn more about how to use Git & GitHub. #54
> Add resource & tutorial links for Git

- README.md
Hi, 
Added more resources for learning Git & GitHub as suggested by @TehSebaXx - #54 
Thanks.
> Add more resource links for Git & GitHub

- src/styles/index.scss
Fixes persistent vertical scroll bar appearing when embedding in iFrame
> Fix persistent vertical scrollbar when embedded

- package.json
- public/index.html
- src/components/GenericCard.js
- src/index.js
- src/views/ServiceRequest.js
- yarn.lock
1. For the vulnerability fix check [this out](https://mathiasbynens.github.io/rel-noopener/).
2. Removed `Roboto` font from `Google CDN` and added `typeface-roboto`. Less API calls.
3. Removed `create-react-app` comments from `index.html`.
Remember to `yarn`.
> Vulnerability's fix and more

- src/components/planningGuideNav.js
- src/styles/planning-guide.scss
> Added breakpoint to hide ScrollSpy Nav
